name: tasks
description: A to-do application.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_value: ^7.0.9
  built_collection: ^4.3.2
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  built_value_generator: ^7.0.9

flutter:
  uses-material-design: true